rule-providers:
  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaCompanyIp.yaml"
    path: ./ACL4SSR/ChinaCompanyIp.yaml
    interval: 86400    

  ChinaIp:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaIp.yaml"
    path: ./ACL4SSR/ChinaIp.yaml
    interval: 86400    

  ProxyGFWlist:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ProxyGFWlist.yaml"
    path: ./ACL4SSR/ProxyGFWlist.yaml
    interval: 86400

  BanAD:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
    path: ./ACL4SSR/BanAD.yaml
    interval: 86400

  BanProgramAD:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
    path: ./ACL4SSR/BanProgramAD.yaml
    interval: 86400

  ChinaDomain:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml"
    path: ./ACL4SSR/ChinaDomain.yaml
    interval: 86400

  LocalAreaNetwork:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml"
    path: ./ACL4SSR/LocalAreaNetwork.yaml
    interval: 86400

  UnBan:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml"
    path: ./ACL4SSR/UnBan.yaml
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml"
    path: ./ACL4SSR/GoogleFCM.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml"
    path: ./ACL4SSR/YouTube.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Google.yaml"
    path: ./ACL4SSR/Google.yaml
    interval: 86400

  GitHub:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Github.yaml"
    path: ./ACL4SSR/GitHub.yaml
    interval: 86400

  Docker:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Docker/Docker.yaml"
    path: ./ACL4SSR/Docker.yaml
    interval: 86400

  OpenAi:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OpenAi.yaml"
    path: ./ACL4SSR/OpenAi.yaml
    interval: 86400

  Claude:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml"
    path: ./ACL4SSR/Claude.yaml
    interval: 86400

  Gemini:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml"
    path: ./ACL4SSR/Gemini.yaml
    interval: 86400

  Bing:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bing.yaml"
    path: ./ACL4SSR/Bing.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml"
    path: ./ACL4SSR/OneDrive.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml"
    path: ./ACL4SSR/Microsoft.yaml
    interval: 86400

  AppleTV:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/AppleTV.yaml"
    path: ./ACL4SSR/AppleTV.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml"
    path: ./ACL4SSR/Apple.yaml
    interval: 86400

  Speedtest:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml"
    path: ./ACL4SSR/Speedtest.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml"
    path: ./ACL4SSR/Telegram.yaml
    interval: 86400

  Discord:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Discord.yaml"
    path: ./ACL4SSR/Discord.yaml
    interval: 86400

  Whatsapp:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Whatsapp.yaml"
    path: ./ACL4SSR/Whatsapp.yaml
    interval: 86400

  TikTok:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/TikTok.yaml"
    path: ./ACL4SSR/TikTok.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml"
    path: ./ACL4SSR/Netflix.yaml
    interval: 86400

  Star-nmz:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/Star-nmz.yaml"
    path: ./ACL4SSR/Star-nmz.yaml
    interval: 86400

  Star-us:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/Star-us.yaml"
    path: ./ACL4SSR/Star-us.yaml
    interval: 86400

  DisneyPlus:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/DisneyPlus.yaml"
    path: ./ACL4SSR/DisneyPlus.yaml
    interval: 86400

  AmazonPrimeVideo:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml"
    path: ./ACL4SSR/AmazonPrimeVideo.yaml
    interval: 86400

  Peacock:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Peacock/Peacock.yaml"
    path: ./ACL4SSR/Peacock.yaml
    interval: 86400

  ParamountPlus:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ParamountPlus/ParamountPlus.yaml"
    path: ./ACL4SSR/ParamountPlus.yaml
    interval: 86400

  FuboTV:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/FuboTV/FuboTV.yaml"
    path: ./ACL4SSR/FuboTV.yaml
    interval: 86400

  Espn:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Espn/Espn.yaml"
    path: ./ACL4SSR/Espn.yaml
    interval: 86400

  HBOUSA:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOUSA/HBOUSA.yaml"
    path: ./ACL4SSR/HBOUSA.yaml
    interval: 86400

  Hulu:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HuluUSA/HuluUSA.yaml"
    path: ./ACL4SSR/Hulu.yaml
    interval: 86400

  AbemaTV:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/AbemaTV.yaml"
    path: ./ACL4SSR/AbemaTV.yaml
    interval: 86400

  ukiptv:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/uk.yaml"
    path: ./ACL4SSR/ukiptv.yaml
    interval: 86400

  BBCiPlayer:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/BBCiPlayer.yaml"
    path: ./ACL4SSR/BBCiPlayer.yaml
    interval: 86400

  ausiptv:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/ausiptv.yaml"
    path: ./ACL4SSR/ausiptv.yaml
    interval: 86400

  myTVSUPER:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/myTVSUPER/myTVSUPER.yaml"
    path: ./ACL4SSR/myTVSUPER.yaml
    interval: 86400

  Tvbanywhere:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/Tvbanywhere.yaml"
    path: ./ACL4SSR/Tvbanywhere.yaml
    interval: 86400

  iQIYIIntl:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iQIYIIntl/iQIYIIntl_No_Resolve.yaml"
    path: ./ACL4SSR/iQIYIIntl.yaml
    interval: 86400

  HamiVideo:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HamiVideo/HamiVideo.yaml"
    path: ./ACL4SSR/HamiVideo.yaml
    interval: 86400

  DAZN:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DAZN/DAZN.yaml"
    path: ./ACL4SSR/DAZN.yaml
    interval: 86400

  Bahamut:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml"
    path: ./ACL4SSR/Bahamut.yaml
    interval: 86400

  BilibiliHMT:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/BilibiliHMT.yaml"
    path: ./ACL4SSR/BilibiliHMT.yaml
    interval: 86400

  Bilibili:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml"
    path: ./ACL4SSR/Bilibili.yaml
    interval: 86400

  RussiaIPTV:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/RussiaIPTV.yaml"
    path: ./ACL4SSR/RussiaIPTV.yaml
    interval: 86400

  EuroIPTV:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/EuroIPTV.yaml"
    path: ./ACL4SSR/EuroIPTV.yaml
    interval: 86400

  USCAIPTV:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/USAIPTV.list"
    path: ./ACL4SSR/USCAIPTV.yaml
    interval: 86400

  astro:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/astro.yaml"
    path: ./ACL4SSR/astro.yaml
    interval: 86400

  Emby:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.yaml"
    path: ./ACL4SSR/Emby.yaml
    interval: 86400

  Plex:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/plex.yaml"
    path: ./ACL4SSR/Plex.yaml
    interval: 86400

  Download:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Download.yaml"
    path: ./ACL4SSR/Download.yaml
    interval: 86400
