rule-providers:
  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaCompanyIp.yaml"
    path: ./ACL4SSR/ChinaCompanyIp.yaml
    interval: 86400    

  ChinaIp:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaIp.yaml"
    path: ./ACL4SSR/ChinaIp.yaml
    interval: 86400    

  ProxyGFWlist:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ProxyGFWlist.yaml"
    path: ./ACL4SSR/ProxyGFWlist.yaml
    interval: 86400

  BanAD:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
    path: ./ACL4SSR/BanAD.yaml
    interval: 86400

  BanProgramAD:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
    path: ./ACL4SSR/BanProgramAD.yaml
    interval: 86400

  ChinaDomain:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml"
    path: ./ACL4SSR/ChinaDomain.yaml
    interval: 86400

  LocalAreaNetwork:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml"
    path: ./ACL4SSR/LocalAreaNetwork.yaml
    interval: 86400

  UnBan:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml"
    path: ./ACL4SSR/UnBan.yaml
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml"
    path: ./ACL4SSR/GoogleFCM.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml"
    path: ./ACL4SSR/YouTube.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Google.yaml"
    path: ./ACL4SSR/Google.yaml
    interval: 86400

  GitHub:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Github.yaml"
    path: ./ACL4SSR/GitHub.yaml
    interval: 86400

  Docker:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Docker/Docker.yaml"
    path: ./ACL4SSR/Docker.yaml
    interval: 86400

  OpenAi:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OpenAi.yaml"
    path: ./ACL4SSR/OpenAi.yaml
    interval: 86400

  Claude:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml"
    path: ./ACL4SSR/Claude.yaml
    interval: 86400

  Bing:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bing.yaml"
    path: ./ACL4SSR/Bing.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml"
    path: ./ACL4SSR/OneDrive.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml"
    path: ./ACL4SSR/Microsoft.yaml
    interval: 86400

  AppleTV:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/AppleTV.yaml"
    path: ./ACL4SSR/AppleTV.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml"
    path: ./ACL4SSR/Apple.yaml
    interval: 86400

  Speedtest:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml"
    path: ./ACL4SSR/Speedtest.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml"
    path: ./ACL4SSR/Telegram.yaml
    interval: 86400

  Discord:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Discord.yaml"
    path: ./ACL4SSR/Discord.yaml
    interval: 86400

  TikTok:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/TikTok.yaml"
    path: ./ACL4SSR/TikTok.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml"
    path: ./ACL4SSR/Game.yaml
    interval: 86400

  Netflix.:
    type: http
    behavior: classical
    url: "https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Providers/Ruleset/Netflix.yaml"
    path: ./ACL4SSR/Netflix..yaml
    interval: 86400

  Star+:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/Star-nmz.yaml"
    path: ./ACL4SSR/Star+.yaml
    interval: 86400

  Star++:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/jack-004/clash-rule/main/rule/clash/Star-us.yaml"
    path: ./ACL4SSR/Star++.yaml
    interval: 86400

  DisneyPlus:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/DisneyPlus.yaml"
    path: ./ACL4SSR/DisneyPlus.yaml
    interval: 86400

  AmazonPrimeVideo:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml"
    path: ./ACL4SSR/AmazonPrimeVideo.yaml
    interval: 86400

  Peacock:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Peacock/Peacock.yaml"
    path: ./ACL4SSR/Peacock.yaml
    interval: 86400

  ParamountPlus:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ParamountPlus/ParamountPlus.yaml"
    path: ./ACL4SSR/ParamountPlus.yaml
    interval: 86400

  FuboTV:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/FuboTV/FuboTV.yaml"
    path: ./ACL4SSR/FuboTV.yaml
    interval: 86400
